spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fellow_travelers
    username: postgres
    password: 111
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

app:
  jwt:
    secret-key: XmRmyPcUVL5VUhR+sfLtbdOvu2tEkGhqEMeKdC7B9LyrQTKa7E8qiROierc7TGVDg6IF0M98wCRt30wXCyjh7A==
    expiration: 86400000 #1 day in ms
    header-name: jwt